name: build-and-release

on:
  push:
    branches:
      - "*" # Triggers the workflow on any branch push

permissions:
  contents: write

env:
  TZ: Asia/Kolkata

jobs:
  build-x86_64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install g++ and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++

      - name: Build C++ application for x86_64
        run: |
          g++ -o udp_flooder_x86_64 udp_flooder.cpp

      - name: Create Tag
        id: create_tag
        run: |
          TAG_NAME=$(echo "${{ github.event.head_commit.message }}" | sed 's/ / - /g')-$(date +%Y%m%d%H%M%S)
          echo "TAG_NAME=${TAG_NAME}" >> $GITHUB_STATE

      - name: Upload Release Asset for x86_64
        uses: actions/upload-artifact@v3
        with:
          name: cpp-binary-x86_64
          path: udp_flooder_x86_64

  build-arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install g++ and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      - name: Build C++ application for arm64
        run: |
          aarch64-linux-gnu-g++ -o udp_flooder_arm64 udp_flooder.cpp

      - name: Upload Release Asset for arm64
        uses: actions/upload-artifact@v3
        with:
          name: cpp-binary-arm64
          path: udp_flooder_arm64

  release:
    needs: [build-x86_64, build-arm64]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.create_tag.outputs.TAG_NAME }}
          release_name: ${{ steps.create_tag.outputs.TAG_NAME }}
          body: |
            Workflow Hash: `${{ github.sha }}`
            Description: Auto-generated release
